/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_settings: {
        Row: {
          user_id: string;
          theme: string;
          accent_color: string;
          font_scale: string;
          motion_pref: string;
          compact_mode: boolean;
          animation_intensity: string;
          sidebar_behavior: string;
          right_panel_behavior: string;
          default_view: string;
          card_density: string;
          table_density: string;
          notifications_enabled: boolean;
          in_app_notifs: boolean;
          email_digest: boolean;
          weekly_reminders: boolean;
          security_logs: boolean;
          upload_notifs: boolean;
          story_notifs: boolean;
          timeline_notifs: boolean;
          playback_quality: string;
          playback_autoplay: boolean;
          playback_mute_by_default: boolean;
          playback_transition_speed: string;
          upload_auto_optimize: boolean;
          upload_max_resolution: string;
          high_contrast: boolean;
          reduced_motion: boolean;
          larger_text: boolean;
          keyboard_navigation: boolean;
          screen_reader: boolean;
          focus_visibility: boolean;
          density: string;
          analytics_enabled: boolean;
          data_sharing: boolean;
          profile_visibility: string;
          story_visibility: string;
          legacy_profile_privacy: string;
          search_visibility: string;
          consent_preferences: boolean;
          two_factor_enabled: boolean;
          auto_save: boolean;
          marketing_consent: boolean;
          archiving_preferences: string;
          account_metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          theme?: string;
          accent_color?: string;
          font_scale?: string;
          motion_pref?: string;
          compact_mode?: boolean;
          animation_intensity?: string;
          sidebar_behavior?: string;
          right_panel_behavior?: string;
          default_view?: string;
          card_density?: string;
          table_density?: string;
          notifications_enabled?: boolean;
          in_app_notifs?: boolean;
          email_digest?: boolean;
          weekly_reminders?: boolean;
          security_logs?: boolean;
          upload_notifs?: boolean;
          story_notifs?: boolean;
          timeline_notifs?: boolean;
          playback_quality?: string;
          playback_autoplay?: boolean;
          playback_mute_by_default?: boolean;
          playback_transition_speed?: string;
          upload_auto_optimize?: boolean;
          upload_max_resolution?: string;
          high_contrast?: boolean;
          reduced_motion?: boolean;
          larger_text?: boolean;
          keyboard_navigation?: boolean;
          screen_reader?: boolean;
          focus_visibility?: boolean;
          density?: string;
          analytics_enabled?: boolean;
          data_sharing?: boolean;
          profile_visibility?: string;
          story_visibility?: string;
          legacy_profile_privacy?: string;
          search_visibility?: string;
          consent_preferences?: boolean;
          two_factor_enabled?: boolean;
          auto_save?: boolean;
          marketing_consent?: boolean;
          archiving_preferences?: string;
          account_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          theme?: string;
          accent_color?: string;
          font_scale?: string;
          motion_pref?: string;
          compact_mode?: boolean;
          animation_intensity?: string;
          sidebar_behavior?: string;
          right_panel_behavior?: string;
          default_view?: string;
          card_density?: string;
          table_density?: string;
          notifications_enabled?: boolean;
          in_app_notifs?: boolean;
          email_digest?: boolean;
          weekly_reminders?: boolean;
          security_logs?: boolean;
          upload_notifs?: boolean;
          story_notifs?: boolean;
          timeline_notifs?: boolean;
          playback_quality?: string;
          playback_autoplay?: boolean;
          playback_mute_by_default?: boolean;
          playback_transition_speed?: string;
          upload_auto_optimize?: boolean;
          upload_max_resolution?: string;
          high_contrast?: boolean;
          reduced_motion?: boolean;
          larger_text?: boolean;
          keyboard_navigation?: boolean;
          screen_reader?: boolean;
          focus_visibility?: boolean;
          density?: string;
          analytics_enabled?: boolean;
          data_sharing?: boolean;
          profile_visibility?: string;
          story_visibility?: string;
          legacy_profile_privacy?: string;
          search_visibility?: string;
          consent_preferences?: boolean;
          two_factor_enabled?: boolean;
          auto_save?: boolean;
          marketing_consent?: boolean;
          archiving_preferences?: string;
          account_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      legacy_profiles: {
        Row: {
          id: string;
          user_id: string;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          preferred_name: string | null;
          nickname: string | null;
          gender: string | null;
          date_of_birth: string;
          place_of_birth: string | null;
          date_of_death: string | null;
          place_of_death: string | null;
          nationality: string | null;
          languages: string[];
          life_status: 'living' | 'memorial' | 'historical';
          category: 'personal' | 'autobiography' | 'memorial' | 'celebration' | 'career' | 'family-history' | 'historical-figure' | 'organization' | 'community';
          relationship: string;
          cover_photo: string | null;
          profile_photo: string | null;
          status: 'draft' | 'published' | 'archived';
          story_progress: number;
          media_count: number;
          timeline_events_count: number;
          document_count: number;
          biography_summary: string | null;
          tags: string[];
          family_members: Json;
          preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          preferred_name?: string | null;
          nickname?: string | null;
          gender?: string | null;
          date_of_birth: string;
          place_of_birth?: string | null;
          date_of_death?: string | null;
          place_of_death?: string | null;
          nationality?: string | null;
          languages?: string[];
          life_status?: 'living' | 'memorial' | 'historical';
          category?: 'personal' | 'autobiography' | 'memorial' | 'celebration' | 'career' | 'family-history' | 'historical-figure' | 'organization' | 'community';
          relationship?: string;
          cover_photo?: string | null;
          profile_photo?: string | null;
          status?: 'draft' | 'published' | 'archived';
          story_progress?: number;
          media_count?: number;
          timeline_events_count?: number;
          document_count?: number;
          biography_summary?: string | null;
          tags?: string[];
          family_members?: Json;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          preferred_name?: string | null;
          nickname?: string | null;
          gender?: string | null;
          date_of_birth?: string;
          place_of_birth?: string | null;
          date_of_death?: string | null;
          place_of_death?: string | null;
          nationality?: string | null;
          languages?: string[];
          life_status?: 'living' | 'memorial' | 'historical';
          category?: 'personal' | 'autobiography' | 'memorial' | 'celebration' | 'career' | 'family-history' | 'historical-figure' | 'organization' | 'community';
          relationship?: string;
          cover_photo?: string | null;
          profile_photo?: string | null;
          status?: 'draft' | 'published' | 'archived';
          story_progress?: number;
          media_count?: number;
          timeline_events_count?: number;
          document_count?: number;
          biography_summary?: string | null;
          tags?: string[];
          family_members?: Json;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      media_collections: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          name: string;
          description: string | null;
          cover_image: string | null;
          asset_count: number;
          tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          name: string;
          description?: string | null;
          cover_image?: string | null;
          asset_count?: number;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          cover_image?: string | null;
          asset_count?: number;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stories: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          narrative_type: string | null;
          category: string;
          theme: string | null;
          mood: string | null;
          narrative_style: string | null;
          primary_language: string | null;
          status: 'draft' | 'in_progress' | 'review' | 'ready_to_render' | 'rendering' | 'published' | 'archived';
          completion_progress: number;
          estimated_duration_seconds: number;
          duration_estimate: string | null;
          cover_image: string | null;
          thumbnail: string | null;
          pinned: boolean;
          favorite: boolean;
          ai_ready: boolean;
          tags: string[];
          categories: string[];
          contributors: Json;
          metadata: Json;
          version: number;
          published_at: string | null;
          last_edited: string;
          last_generated: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          narrative_type?: string | null;
          category?: string;
          theme?: string | null;
          mood?: string | null;
          narrative_style?: string | null;
          primary_language?: string | null;
          status?: 'draft' | 'in_progress' | 'review' | 'ready_to_render' | 'rendering' | 'published' | 'archived';
          completion_progress?: number;
          estimated_duration_seconds?: number;
          duration_estimate?: string | null;
          cover_image?: string | null;
          thumbnail?: string | null;
          pinned?: boolean;
          favorite?: boolean;
          ai_ready?: boolean;
          tags?: string[];
          categories?: string[];
          contributors?: Json;
          metadata?: Json;
          version?: number;
          published_at?: string | null;
          last_edited?: string;
          last_generated?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          narrative_type?: string | null;
          category?: string;
          theme?: string | null;
          mood?: string | null;
          narrative_style?: string | null;
          primary_language?: string | null;
          status?: 'draft' | 'in_progress' | 'review' | 'ready_to_render' | 'rendering' | 'published' | 'archived';
          completion_progress?: number;
          estimated_duration_seconds?: number;
          duration_estimate?: string | null;
          cover_image?: string | null;
          thumbnail?: string | null;
          pinned?: boolean;
          favorite?: boolean;
          ai_ready?: boolean;
          tags?: string[];
          categories?: string[];
          contributors?: Json;
          metadata?: Json;
          version?: number;
          published_at?: string | null;
          last_edited?: string;
          last_generated?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      story_characters: {
        Row: {
          id: string;
          story_id: string;
          legacy_profile_id: string | null;
          name: string;
          story_role: string;
          relationship: string;
          importance: string;
          avatar: string | null;
          short_bio: string | null;
          notes: string | null;
          lifetime: string | null;
          narrative_weight: number;
          status: string;
          tags: string[];
          timeline_references: string[];
          media_references: string[];
          quotes_count: number;
          scenes_count: number;
          estimated_screen_time: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          legacy_profile_id?: string | null;
          name: string;
          story_role?: string;
          relationship?: string;
          importance?: string;
          avatar?: string | null;
          short_bio?: string | null;
          notes?: string | null;
          lifetime?: string | null;
          narrative_weight?: number;
          status?: string;
          tags?: string[];
          timeline_references?: string[];
          media_references?: string[];
          quotes_count?: number;
          scenes_count?: number;
          estimated_screen_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          legacy_profile_id?: string | null;
          name?: string;
          story_role?: string;
          relationship?: string;
          importance?: string;
          avatar?: string | null;
          short_bio?: string | null;
          notes?: string | null;
          lifetime?: string | null;
          narrative_weight?: number;
          status?: string;
          tags?: string[];
          timeline_references?: string[];
          media_references?: string[];
          quotes_count?: number;
          scenes_count?: number;
          estimated_screen_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      character_relationships: {
        Row: {
          id: string;
          story_id: string;
          from_character_id: string;
          to_character_id: string;
          relation_type: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          from_character_id: string;
          to_character_id: string;
          relation_type?: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          from_character_id?: string;
          to_character_id?: string;
          relation_type?: string;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      story_chapters: {
        Row: {
          id: string;
          story_id: string;
          title: string;
          summary: string | null;
          order_index: number;
          time_period: string | null;
          estimated_duration_seconds: number;
          duration: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          title: string;
          summary?: string | null;
          order_index?: number;
          time_period?: string | null;
          estimated_duration_seconds?: number;
          duration?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          title?: string;
          summary?: string | null;
          order_index?: number;
          time_period?: string | null;
          estimated_duration_seconds?: number;
          duration?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      story_scenes: {
        Row: {
          id: string;
          chapter_id: string;
          story_id: string;
          scene_number: number;
          title: string;
          subtitle: string | null;
          description: string | null;
          purpose: string | null;
          story_segment: string;
          scene_type: string;
          estimated_duration: string | null;
          duration_seconds: number;
          notes: string | null;
          status: string;
          layout: string;
          narration_text: string | null;
          narration_status: string;
          assigned_voice: string | null;
          estimated_reading_time: string | null;
          music_track: string | null;
          music_mood: string | null;
          music_volume: number;
          fade_in: boolean;
          fade_out: boolean;
          camera_movement: string | null;
          zoom_style: string | null;
          pan_direction: string | null;
          focus_point: string | null;
          transition_type: string | null;
          primary_character_id: string | null;
          quotes: string[];
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          chapter_id: string;
          story_id: string;
          scene_number?: number;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          purpose?: string | null;
          story_segment?: string;
          scene_type?: string;
          estimated_duration?: string | null;
          duration_seconds?: number;
          notes?: string | null;
          status?: string;
          layout?: string;
          narration_text?: string | null;
          narration_status?: string;
          assigned_voice?: string | null;
          estimated_reading_time?: string | null;
          music_track?: string | null;
          music_mood?: string | null;
          music_volume?: number;
          fade_in?: boolean;
          fade_out?: boolean;
          camera_movement?: string | null;
          zoom_style?: string | null;
          pan_direction?: string | null;
          focus_point?: string | null;
          transition_type?: string | null;
          primary_character_id?: string | null;
          quotes?: string[];
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          chapter_id?: string;
          story_id?: string;
          scene_number?: number;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          purpose?: string | null;
          story_segment?: string;
          scene_type?: string;
          estimated_duration?: string | null;
          duration_seconds?: number;
          notes?: string | null;
          status?: string;
          layout?: string;
          narration_text?: string | null;
          narration_status?: string;
          assigned_voice?: string | null;
          estimated_reading_time?: string | null;
          music_track?: string | null;
          music_mood?: string | null;
          music_volume?: number;
          fade_in?: boolean;
          fade_out?: boolean;
          camera_movement?: string | null;
          zoom_style?: string | null;
          pan_direction?: string | null;
          focus_point?: string | null;
          transition_type?: string | null;
          primary_character_id?: string | null;
          quotes?: string[];
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      story_scene_media: {
        Row: {
          scene_id: string;
          media_asset_id: string;
          layer_order: number;
          asset_role: string;
          animation_effect: string | null;
          caption: string | null;
          created_at: string;
        };
        Insert: {
          scene_id: string;
          media_asset_id: string;
          layer_order?: number;
          asset_role?: string;
          animation_effect?: string | null;
          caption?: string | null;
          created_at?: string;
        };
        Update: {
          scene_id?: string;
          media_asset_id?: string;
          layer_order?: number;
          asset_role?: string;
          animation_effect?: string | null;
          caption?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      story_scene_characters: {
        Row: {
          scene_id: string;
          character_id: string;
          role_in_scene: string | null;
          appearance_notes: string | null;
          created_at: string;
        };
        Insert: {
          scene_id: string;
          character_id: string;
          role_in_scene?: string | null;
          appearance_notes?: string | null;
          created_at?: string;
        };
        Update: {
          scene_id?: string;
          character_id?: string;
          role_in_scene?: string | null;
          appearance_notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      media_assets: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          collection_id: string | null;
          linked_story_id: string | null;
          name: string;
          display_name: string | null;
          original_filename: string | null;
          file_url: string;
          storage_path: string;
          media_type: 'image' | 'video' | 'audio' | 'document';
          mime_type: string;
          extension: string | null;
          file_size_bytes: number;
          width: number | null;
          height: number | null;
          resolution: string | null;
          duration_seconds: number | null;
          blurhash: string | null;
          thumbnail_url: string | null;
          description: string | null;
          status: 'Uploading' | 'Optimizing' | 'Ready' | 'Needs Metadata' | 'Flagged' | 'Error';
          favorite: boolean;
          archived: boolean;
          tags: string[];
          categories: string[];
          linked_events: string[];
          linked_chapters: string[];
          exif_data: Json;
          ai_metadata: Json;
          metadata: Json;
          captured_date: string | null;
          captured_location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          collection_id?: string | null;
          linked_story_id?: string | null;
          name: string;
          display_name?: string | null;
          original_filename?: string | null;
          file_url: string;
          storage_path?: string;
          media_type?: 'image' | 'video' | 'audio' | 'document';
          mime_type?: string;
          extension?: string | null;
          file_size_bytes?: number;
          width?: number | null;
          height?: number | null;
          resolution?: string | null;
          duration_seconds?: number | null;
          blurhash?: string | null;
          thumbnail_url?: string | null;
          description?: string | null;
          status?: 'Uploading' | 'Optimizing' | 'Ready' | 'Needs Metadata' | 'Flagged' | 'Error';
          favorite?: boolean;
          archived?: boolean;
          tags?: string[];
          categories?: string[];
          linked_events?: string[];
          linked_chapters?: string[];
          exif_data?: Json;
          ai_metadata?: Json;
          metadata?: Json;
          captured_date?: string | null;
          captured_location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          collection_id?: string | null;
          linked_story_id?: string | null;
          name?: string;
          display_name?: string | null;
          original_filename?: string | null;
          file_url?: string;
          storage_path?: string;
          media_type?: 'image' | 'video' | 'audio' | 'document';
          mime_type?: string;
          extension?: string | null;
          file_size_bytes?: number;
          width?: number | null;
          height?: number | null;
          resolution?: string | null;
          duration_seconds?: number | null;
          blurhash?: string | null;
          thumbnail_url?: string | null;
          description?: string | null;
          status?: 'Uploading' | 'Optimizing' | 'Ready' | 'Needs Metadata' | 'Flagged' | 'Error';
          favorite?: boolean;
          archived?: boolean;
          tags?: string[];
          categories?: string[];
          linked_events?: string[];
          linked_chapters?: string[];
          exif_data?: Json;
          ai_metadata?: Json;
          metadata?: Json;
          captured_date?: string | null;
          captured_location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_documents: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          story_id: string | null;
          timeline_event_id: string | null;
          original_filename: string;
          display_name: string;
          document_type: string;
          category: string;
          mime_type: string;
          extension: string | null;
          file_size_bytes: number;
          file_size_formatted: string | null;
          storage_path: string;
          file_url: string;
          description: string | null;
          extracted_text: string | null;
          ai_summary: string | null;
          page_count: number | null;
          tags: string[];
          categories: string[];
          favorite: boolean;
          archived: boolean;
          metadata: Json;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          story_id?: string | null;
          timeline_event_id?: string | null;
          original_filename: string;
          display_name: string;
          document_type?: string;
          category?: string;
          mime_type: string;
          extension?: string | null;
          file_size_bytes?: number;
          file_size_formatted?: string | null;
          storage_path?: string;
          file_url: string;
          description?: string | null;
          extracted_text?: string | null;
          ai_summary?: string | null;
          page_count?: number | null;
          tags?: string[];
          categories?: string[];
          favorite?: boolean;
          archived?: boolean;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          story_id?: string | null;
          timeline_event_id?: string | null;
          original_filename?: string;
          display_name?: string;
          document_type?: string;
          category?: string;
          mime_type?: string;
          extension?: string | null;
          file_size_bytes?: number;
          file_size_formatted?: string | null;
          storage_path?: string;
          file_url?: string;
          description?: string | null;
          extracted_text?: string | null;
          ai_summary?: string | null;
          page_count?: number | null;
          tags?: string[];
          categories?: string[];
          favorite?: boolean;
          archived?: boolean;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_imports: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          story_id: string | null;
          original_filename: string;
          display_name: string;
          import_type: string;
          mime_type: string;
          extension: string | null;
          file_size_bytes: number;
          storage_path: string;
          file_url: string;
          description: string | null;
          import_status: string;
          tags: string[];
          categories: string[];
          favorite: boolean;
          archived: boolean;
          metadata: Json;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          story_id?: string | null;
          original_filename: string;
          display_name: string;
          import_type: string;
          mime_type: string;
          extension?: string | null;
          file_size_bytes?: number;
          storage_path?: string;
          file_url: string;
          description?: string | null;
          import_status?: string;
          tags?: string[];
          categories?: string[];
          favorite?: boolean;
          archived?: boolean;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          story_id?: string | null;
          original_filename?: string;
          display_name?: string;
          import_type?: string;
          mime_type?: string;
          extension?: string | null;
          file_size_bytes?: number;
          storage_path?: string;
          file_url?: string;
          description?: string | null;
          import_status?: string;
          tags?: string[];
          categories?: string[];
          favorite?: boolean;
          archived?: boolean;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      timeline_events: {
        Row: {
          id: string;
          profile_id: string;
          user_id: string;
          story_id: string | null;
          year: string;
          event_date: string | null;
          title: string;
          subtitle: string | null;
          description: string;
          category: string;
          event_type: string | null;
          location: string | null;
          importance: string;
          milestone: boolean;
          people_involved: string[];
          supporting_media_ids: string[];
          document_ids: string[];
          tags: string[];
          categories: string[];
          visibility: string | null;
          status: string | null;
          sort_order: number | null;
          metadata: Json;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          user_id?: string;
          story_id?: string | null;
          year: string;
          event_date?: string | null;
          title: string;
          subtitle?: string | null;
          description: string;
          category?: string;
          event_type?: string | null;
          location?: string | null;
          importance?: string;
          milestone?: boolean;
          people_involved?: string[];
          supporting_media_ids?: string[];
          document_ids?: string[];
          tags?: string[];
          categories?: string[];
          visibility?: string | null;
          status?: string | null;
          sort_order?: number | null;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          user_id?: string;
          story_id?: string | null;
          year?: string;
          event_date?: string | null;
          title?: string;
          subtitle?: string | null;
          description?: string;
          category?: string;
          event_type?: string | null;
          location?: string | null;
          importance?: string;
          milestone?: boolean;
          people_involved?: string[];
          supporting_media_ids?: string[];
          document_ids?: string[];
          tags?: string[];
          categories?: string[];
          visibility?: string | null;
          status?: string | null;
          sort_order?: number | null;
          metadata?: Json;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      voice_profiles: {
        Row: {
          id: string;
          user_id: string | null;
          is_system_preset: boolean;
          name: string;
          title: string | null;
          category: string;
          avatar: string | null;
          gender: string;
          age_group: string | null;
          accent: string;
          description: string;
          speed: number;
          pitch: number;
          stability: number;
          emotion: string;
          pause_style: string;
          tags: string[];
          sample_audio_url: string | null;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          is_system_preset?: boolean;
          name: string;
          title?: string | null;
          category?: string;
          avatar?: string | null;
          gender?: string;
          age_group?: string | null;
          accent?: string;
          description?: string;
          speed?: number;
          pitch?: number;
          stability?: number;
          emotion?: string;
          pause_style?: string;
          tags?: string[];
          sample_audio_url?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          is_system_preset?: boolean;
          name?: string;
          title?: string | null;
          category?: string;
          avatar?: string | null;
          gender?: string;
          age_group?: string | null;
          accent?: string;
          description?: string;
          speed?: number;
          pitch?: number;
          stability?: number;
          emotion?: string;
          pause_style?: string;
          tags?: string[];
          sample_audio_url?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      narration_projects: {
        Row: {
          id: string;
          story_id: string;
          voice_profile_id: string | null;
          voice_settings: Json;
          pronunciation_rules: Json;
          background_music_track: string | null;
          music_ducking_db: number;
          master_volume: number;
          status: string;
          stats: Json;
          export_settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          voice_profile_id?: string | null;
          voice_settings?: Json;
          pronunciation_rules?: Json;
          background_music_track?: string | null;
          music_ducking_db?: number;
          master_volume?: number;
          status?: string;
          stats?: Json;
          export_settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          voice_profile_id?: string | null;
          voice_settings?: Json;
          pronunciation_rules?: Json;
          background_music_track?: string | null;
          music_ducking_db?: number;
          master_volume?: number;
          status?: string;
          stats?: Json;
          export_settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      narration_segments: {
        Row: {
          id: string;
          project_id: string;
          scene_id: string;
          order_index: number;
          act_title: string | null;
          chapter_title: string | null;
          scene_title: string | null;
          text: string;
          speaking_duration_estimate_sec: number;
          actual_duration_sec: number;
          word_count: number;
          reading_difficulty: string;
          tone: string;
          pronunciation_hints: string[];
          character_references: string[];
          timeline_references: string[];
          active_voice_id: string | null;
          status: string;
          active_version_id: string | null;
          versions: Json;
          subtitles: Json;
          audio_quality_score: number;
          quality_issues: Json;
          music_ducking_db: number;
          waveform_data: number[];
          ai_suggestions: Json;
          last_edited: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          scene_id: string;
          order_index?: number;
          act_title?: string | null;
          chapter_title?: string | null;
          scene_title?: string | null;
          text: string;
          speaking_duration_estimate_sec?: number;
          actual_duration_sec?: number;
          word_count?: number;
          reading_difficulty?: string;
          tone?: string;
          pronunciation_hints?: string[];
          character_references?: string[];
          timeline_references?: string[];
          active_voice_id?: string | null;
          status?: string;
          active_version_id?: string | null;
          versions?: Json;
          subtitles?: Json;
          audio_quality_score?: number;
          quality_issues?: Json;
          music_ducking_db?: number;
          waveform_data?: number[];
          ai_suggestions?: Json;
          last_edited?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          scene_id?: string;
          order_index?: number;
          act_title?: string | null;
          chapter_title?: string | null;
          scene_title?: string | null;
          text?: string;
          speaking_duration_estimate_sec?: number;
          actual_duration_sec?: number;
          word_count?: number;
          reading_difficulty?: string;
          tone?: string;
          pronunciation_hints?: string[];
          character_references?: string[];
          timeline_references?: string[];
          active_voice_id?: string | null;
          status?: string;
          active_version_id?: string | null;
          versions?: Json;
          subtitles?: Json;
          audio_quality_score?: number;
          quality_issues?: Json;
          music_ducking_db?: number;
          waveform_data?: number[];
          ai_suggestions?: Json;
          last_edited?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      render_jobs: {
        Row: {
          id: string;
          story_id: string;
          user_id: string;
          story_name: string;
          version: string;
          type: string;
          resolution: string;
          format: string;
          status: string;
          priority: string;
          progress: number;
          current_stage: string;
          stages: Json;
          preflight_checks: Json;
          duration_sec: number;
          render_time_sec: number;
          output_file_size_mb: number | null;
          output_destination: string;
          output_file_url: string | null;
          thumbnail_url: string | null;
          assigned_template: string | null;
          profile_name: string;
          logs: string[];
          ai_suggestions: string[];
          checksum: string | null;
          tags: string[];
          error_details: string | null;
          scheduled_for: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          user_id?: string;
          story_name: string;
          version?: string;
          type?: string;
          resolution?: string;
          format?: string;
          status?: string;
          priority?: string;
          progress?: number;
          current_stage?: string;
          stages?: Json;
          preflight_checks?: Json;
          duration_sec?: number;
          render_time_sec?: number;
          output_file_size_mb?: number | null;
          output_destination?: string;
          output_file_url?: string | null;
          thumbnail_url?: string | null;
          assigned_template?: string | null;
          profile_name?: string;
          logs?: string[];
          ai_suggestions?: string[];
          checksum?: string | null;
          tags?: string[];
          error_details?: string | null;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          user_id?: string;
          story_name?: string;
          version?: string;
          type?: string;
          resolution?: string;
          format?: string;
          status?: string;
          priority?: string;
          progress?: number;
          current_stage?: string;
          stages?: Json;
          preflight_checks?: Json;
          duration_sec?: number;
          render_time_sec?: number;
          output_file_size_mb?: number | null;
          output_destination?: string;
          output_file_url?: string | null;
          thumbnail_url?: string | null;
          assigned_template?: string | null;
          profile_name?: string;
          logs?: string[];
          ai_suggestions?: string[];
          checksum?: string | null;
          tags?: string[];
          error_details?: string | null;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      story_templates: {
        Row: {
          id: string;
          author_user_id: string | null;
          is_system_preset: boolean;
          name: string;
          description: string;
          cover_image: string | null;
          category: string;
          difficulty: string;
          estimated_runtime: string;
          scene_count: number;
          chapter_count: number;
          act_count: number;
          story_type: string;
          recommended_audience: string;
          popularity: number;
          ai_compatibility: string;
          is_featured: boolean;
          is_popular: boolean;
          is_community: boolean;
          is_favorite: boolean;
          rating: number | null;
          tags: string[];
          narrative_blueprint: Json;
          version: string;
          version_history: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_user_id?: string | null;
          is_system_preset?: boolean;
          name: string;
          description?: string;
          cover_image?: string | null;
          category?: string;
          difficulty?: string;
          estimated_runtime?: string;
          scene_count?: number;
          chapter_count?: number;
          act_count?: number;
          story_type?: string;
          recommended_audience?: string;
          popularity?: number;
          ai_compatibility?: string;
          is_featured?: boolean;
          is_popular?: boolean;
          is_community?: boolean;
          is_favorite?: boolean;
          rating?: number | null;
          tags?: string[];
          narrative_blueprint?: Json;
          version?: string;
          version_history?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_user_id?: string | null;
          is_system_preset?: boolean;
          name?: string;
          description?: string;
          cover_image?: string | null;
          category?: string;
          difficulty?: string;
          estimated_runtime?: string;
          scene_count?: number;
          chapter_count?: number;
          act_count?: number;
          story_type?: string;
          recommended_audience?: string;
          popularity?: number;
          ai_compatibility?: string;
          is_featured?: boolean;
          is_popular?: boolean;
          is_community?: boolean;
          is_favorite?: boolean;
          rating?: number | null;
          tags?: string[];
          narrative_blueprint?: Json;
          version?: string;
          version_history?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      activity_logs: {
        Row: {
          id: string;
          user_id: string;
          profile_id: string | null;
          story_id: string | null;
          title: string;
          description: string;
          icon_color: string;
          action_type: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          profile_id?: string | null;
          story_id?: string | null;
          title: string;
          description: string;
          icon_color?: string;
          action_type?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          profile_id?: string | null;
          story_id?: string | null;
          title?: string;
          description?: string;
          icon_color?: string;
          action_type?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: 'info' | 'success' | 'warning' | 'error';
          is_read: boolean;
          action_url: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          title: string;
          message: string;
          type?: 'info' | 'success' | 'warning' | 'error';
          is_read?: boolean;
          action_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: 'info' | 'success' | 'warning' | 'error';
          is_read?: boolean;
          action_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      story_shares: {
        Row: {
          id: string;
          story_id: string;
          created_by: string;
          share_token: string;
          access_level: 'view_only' | 'comment' | 'collaborate' | 'co_author';
          password_protected: boolean;
          password_hash: string | null;
          expires_at: string | null;
          view_count: number;
          max_views: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          created_by?: string;
          share_token?: string;
          access_level?: 'view_only' | 'comment' | 'collaborate' | 'co_author';
          password_protected?: boolean;
          password_hash?: string | null;
          expires_at?: string | null;
          view_count?: number;
          max_views?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          created_by?: string;
          share_token?: string;
          access_level?: 'view_only' | 'comment' | 'collaborate' | 'co_author';
          password_protected?: boolean;
          password_hash?: string | null;
          expires_at?: string | null;
          view_count?: number;
          max_views?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
