-- ==============================================================================
-- REELLEGACY PRODUCTION DATABASE MIGRATION PACKAGE
-- Migration: 002_core_tables.sql
-- Description: Core entity tables (user_settings, legacy_profiles, media_collections,
--              stories, story_characters, media_assets, source_documents, source_imports,
--              story_chapters, story_scenes)
-- Target Backend: Supabase / PostgreSQL 15+
-- ==============================================================================

-- 1. USER SETTINGS (1:1 with auth.users)
CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    theme TEXT NOT NULL DEFAULT 'system',
    accent_color TEXT NOT NULL DEFAULT '#E5A93C',
    font_scale TEXT NOT NULL DEFAULT 'medium',
    motion_pref TEXT NOT NULL DEFAULT 'smooth',
    compact_mode BOOLEAN NOT NULL DEFAULT false,
    animation_intensity TEXT NOT NULL DEFAULT 'moderate',
    sidebar_behavior TEXT NOT NULL DEFAULT 'expanded',
    right_panel_behavior TEXT NOT NULL DEFAULT 'collapsible',
    default_view TEXT NOT NULL DEFAULT 'dashboard',
    card_density TEXT NOT NULL DEFAULT 'standard',
    table_density TEXT NOT NULL DEFAULT 'standard',
    notifications_enabled BOOLEAN NOT NULL DEFAULT true,
    in_app_notifs BOOLEAN NOT NULL DEFAULT true,
    email_digest BOOLEAN NOT NULL DEFAULT false,
    weekly_reminders BOOLEAN NOT NULL DEFAULT true,
    security_logs BOOLEAN NOT NULL DEFAULT true,
    upload_notifs BOOLEAN NOT NULL DEFAULT true,
    story_notifs BOOLEAN NOT NULL DEFAULT true,
    timeline_notifs BOOLEAN NOT NULL DEFAULT true,
    playback_quality TEXT NOT NULL DEFAULT 'auto',
    playback_autoplay BOOLEAN NOT NULL DEFAULT true,
    playback_mute_by_default BOOLEAN NOT NULL DEFAULT false,
    playback_transition_speed TEXT NOT NULL DEFAULT 'normal',
    upload_auto_optimize BOOLEAN NOT NULL DEFAULT true,
    upload_max_resolution TEXT NOT NULL DEFAULT '4K',
    high_contrast BOOLEAN NOT NULL DEFAULT false,
    reduced_motion BOOLEAN NOT NULL DEFAULT false,
    larger_text BOOLEAN NOT NULL DEFAULT false,
    keyboard_navigation BOOLEAN NOT NULL DEFAULT true,
    screen_reader BOOLEAN NOT NULL DEFAULT false,
    focus_visibility BOOLEAN NOT NULL DEFAULT true,
    density TEXT NOT NULL DEFAULT 'standard',
    analytics_enabled BOOLEAN NOT NULL DEFAULT true,
    data_sharing BOOLEAN NOT NULL DEFAULT false,
    profile_visibility TEXT NOT NULL DEFAULT 'private',
    story_visibility TEXT NOT NULL DEFAULT 'private',
    legacy_profile_privacy TEXT NOT NULL DEFAULT 'family-only',
    search_visibility TEXT NOT NULL DEFAULT 'unlisted',
    consent_preferences BOOLEAN NOT NULL DEFAULT true,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT false,
    auto_save BOOLEAN NOT NULL DEFAULT true,
    marketing_consent BOOLEAN NOT NULL DEFAULT false,
    archiving_preferences TEXT NOT NULL DEFAULT 'standard',
    account_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. LEGACY PROFILES (Tenant Anchor per Heritage/Family Subject)
CREATE TABLE IF NOT EXISTS legacy_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    middle_name TEXT,
    last_name TEXT NOT NULL,
    preferred_name TEXT,
    nickname TEXT,
    gender TEXT,
    date_of_birth DATE NOT NULL,
    place_of_birth TEXT,
    date_of_death DATE,
    place_of_death TEXT,
    nationality TEXT,
    languages TEXT[] NOT NULL DEFAULT '{}',
    life_status life_status NOT NULL DEFAULT 'living',
    category profile_category NOT NULL DEFAULT 'personal',
    relationship TEXT NOT NULL DEFAULT 'Self',
    cover_photo TEXT,
    profile_photo TEXT,
    status profile_status NOT NULL DEFAULT 'draft',
    story_progress INTEGER NOT NULL DEFAULT 0 CHECK (story_progress >= 0 AND story_progress <= 100),
    media_count INTEGER NOT NULL DEFAULT 0 CHECK (media_count >= 0),
    timeline_events_count INTEGER NOT NULL DEFAULT 0 CHECK (timeline_events_count >= 0),
    document_count INTEGER NOT NULL DEFAULT 0 CHECK (document_count >= 0),
    biography_summary TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    family_members JSONB NOT NULL DEFAULT '[]'::jsonb,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_profile_death_after_birth CHECK (date_of_death IS NULL OR date_of_death >= date_of_birth)
);

-- 3. MEDIA COLLECTIONS
CREATE TABLE IF NOT EXISTS media_collections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES legacy_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    cover_image TEXT,
    asset_count INTEGER NOT NULL DEFAULT 0 CHECK (asset_count >= 0),
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. STORIES
CREATE TABLE IF NOT EXISTS stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES legacy_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    narrative_type TEXT DEFAULT 'biographical_chronicle',
    category TEXT NOT NULL DEFAULT 'Family Legacy',
    theme TEXT,
    mood TEXT,
    narrative_style TEXT,
    primary_language TEXT DEFAULT 'en-US',
    status story_status NOT NULL DEFAULT 'draft',
    completion_progress INTEGER NOT NULL DEFAULT 0 CHECK (completion_progress >= 0 AND completion_progress <= 100),
    estimated_duration_seconds INTEGER NOT NULL DEFAULT 0 CHECK (estimated_duration_seconds >= 0),
    duration_estimate TEXT,
    cover_image TEXT,
    thumbnail TEXT,
    pinned BOOLEAN NOT NULL DEFAULT false,
    favorite BOOLEAN NOT NULL DEFAULT false,
    ai_ready BOOLEAN NOT NULL DEFAULT false,
    tags TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    contributors JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version INTEGER NOT NULL DEFAULT 1,
    published_at TIMESTAMPTZ,
    last_edited TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_generated TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. STORY CHARACTERS (First-Class Relational Entity scoped directly to Story)
CREATE TABLE IF NOT EXISTS story_characters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    legacy_profile_id UUID REFERENCES legacy_profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    story_role character_role NOT NULL DEFAULT 'Main Subject',
    relationship character_relation_type NOT NULL DEFAULT 'Other',
    importance character_importance NOT NULL DEFAULT 'Medium',
    avatar TEXT,
    short_bio TEXT,
    notes TEXT,
    lifetime TEXT,
    narrative_weight INTEGER NOT NULL DEFAULT 50 CHECK (narrative_weight >= 0 AND narrative_weight <= 100),
    status character_status NOT NULL DEFAULT 'Active',
    tags TEXT[] NOT NULL DEFAULT '{}',
    timeline_references TEXT[] NOT NULL DEFAULT '{}',
    media_references TEXT[] NOT NULL DEFAULT '{}',
    quotes_count INTEGER NOT NULL DEFAULT 0,
    scenes_count INTEGER NOT NULL DEFAULT 0,
    estimated_screen_time TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. MEDIA ASSETS
CREATE TABLE IF NOT EXISTS media_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES legacy_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    collection_id UUID REFERENCES media_collections(id) ON DELETE SET NULL,
    linked_story_id UUID REFERENCES stories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    display_name TEXT,
    original_filename TEXT,
    file_url TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    media_type media_type NOT NULL DEFAULT 'image',
    mime_type TEXT NOT NULL,
    extension TEXT,
    file_size_bytes BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    width INTEGER,
    height INTEGER,
    resolution TEXT,
    duration_seconds INTEGER CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    blurhash TEXT,
    thumbnail_url TEXT,
    description TEXT,
    status media_status NOT NULL DEFAULT 'Ready',
    favorite BOOLEAN NOT NULL DEFAULT false,
    archived BOOLEAN NOT NULL DEFAULT false,
    tags TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    linked_events TEXT[] NOT NULL DEFAULT '{}',
    linked_chapters TEXT[] NOT NULL DEFAULT '{}',
    exif_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    ai_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_date DATE,
    captured_location TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. SOURCE DOCUMENTS (Grounding and Archival Transcripts for AI Storytelling)
CREATE TABLE IF NOT EXISTS source_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES legacy_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    story_id UUID REFERENCES stories(id) ON DELETE SET NULL,
    timeline_event_id UUID,
    original_filename TEXT NOT NULL,
    display_name TEXT NOT NULL,
    document_type TEXT NOT NULL DEFAULT 'other',
    category document_category NOT NULL DEFAULT 'other',
    mime_type TEXT NOT NULL,
    extension TEXT,
    file_size_bytes BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    file_size_formatted TEXT,
    storage_path TEXT NOT NULL,
    file_url TEXT NOT NULL,
    description TEXT,
    extracted_text TEXT,
    ai_summary TEXT,
    page_count INTEGER DEFAULT 1,
    tags TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    favorite BOOLEAN NOT NULL DEFAULT false,
    archived BOOLEAN NOT NULL DEFAULT false,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 8. SOURCE IMPORTS
CREATE TABLE IF NOT EXISTS source_imports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES legacy_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    story_id UUID REFERENCES stories(id) ON DELETE SET NULL,
    original_filename TEXT NOT NULL,
    display_name TEXT NOT NULL,
    import_type TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    extension TEXT,
    file_size_bytes BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    storage_path TEXT NOT NULL,
    file_url TEXT NOT NULL,
    description TEXT,
    import_status import_status NOT NULL DEFAULT 'Pending',
    tags TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    favorite BOOLEAN NOT NULL DEFAULT false,
    archived BOOLEAN NOT NULL DEFAULT false,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 9. STORY CHAPTERS
CREATE TABLE IF NOT EXISTS story_chapters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT,
    order_index INTEGER NOT NULL DEFAULT 0,
    time_period TEXT,
    estimated_duration_seconds INTEGER NOT NULL DEFAULT 0 CHECK (estimated_duration_seconds >= 0),
    duration TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_story_chapter_order UNIQUE (story_id, order_index) DEFERRABLE INITIALLY DEFERRED
);

-- 10. STORY SCENES
CREATE TABLE IF NOT EXISTS story_scenes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chapter_id UUID NOT NULL REFERENCES story_chapters(id) ON DELETE CASCADE,
    story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    scene_number INTEGER NOT NULL DEFAULT 1,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    purpose TEXT,
    story_segment TEXT NOT NULL DEFAULT 'Opening Sequence',
    scene_type TEXT NOT NULL DEFAULT 'Documentary',
    estimated_duration TEXT DEFAULT '1m 00s',
    duration_seconds INTEGER NOT NULL DEFAULT 60 CHECK (duration_seconds > 0),
    notes TEXT,
    status scene_status NOT NULL DEFAULT 'Draft',
    layout scene_layout NOT NULL DEFAULT 'standard',
    narration_text TEXT,
    narration_status narration_status NOT NULL DEFAULT 'Draft',
    assigned_voice TEXT,
    estimated_reading_time TEXT,
    music_track TEXT,
    music_mood TEXT,
    music_volume INTEGER NOT NULL DEFAULT 70 CHECK (music_volume >= 0 AND music_volume <= 100),
    fade_in BOOLEAN NOT NULL DEFAULT true,
    fade_out BOOLEAN NOT NULL DEFAULT true,
    camera_movement TEXT DEFAULT 'Slow Ken Burns Pan',
    zoom_style TEXT DEFAULT 'Subtle (1.05x)',
    pan_direction TEXT DEFAULT 'Left to Right',
    focus_point TEXT DEFAULT 'Center',
    transition_type TEXT DEFAULT 'Cross Dissolve',
    primary_character_id UUID REFERENCES story_characters(id) ON DELETE SET NULL,
    quotes TEXT[] NOT NULL DEFAULT '{}',
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_chapter_scene_order UNIQUE (chapter_id, scene_number) DEFERRABLE INITIALLY DEFERRED
);
